

CREATE TABLE EventTypes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type NVARCHAR2(125) NOT NULL
);

CREATE TABLE HomeworkExecutionStatuses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type NVARCHAR2(125) NOT NULL
);

CREATE TABLE HomeworkStatuses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status NVARCHAR2(125) NOT NULL
);

CREATE TABLE HomeworkTypes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type NVARCHAR2(125) NOT NULL
);

CREATE TABLE CurseStatuses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status NVARCHAR2(125) NOT NULL
);




CREATE TABLE Users(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name NVARCHAR2(125) NOT NULL,
    surname NVARCHAR2(125) NOT NULL,
    father_name NVARCHAR2(125),
    email NVARCHAR2(256) NOT NULL UNIQUE,
    passwordHASH RAW(128) NOT NULL,
    birthDay DATE NOT NULL,
    avatarURI NVARCHAR2(512),
    bio NVARCHAR2(2000),
    role NUMBER NOT NULL,
    isDeleted NUMBER(1) DEFAULT 0
);

CREATE TABLE Courses(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Status NUMBER NOT NULL,
    curseName NVARCHAR2(256) NOT NULL,
    description NVARCHAR2(2000),
    DateOfBegin DATE NOT NULL,
    HeaderURL NVARCHAR2(1000),
    price NUMBER(10,2) NOT NULL,

    CONSTRAINT FK_Courses_Status
        FOREIGN KEY (Status)
        REFERENCES CurseStatuses(id)
);

CREATE TABLE Schedule(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventType NUMBER NOT NULL,
    curseID NUMBER NOT NULL,
    eventDate DATE NOT NULL,
    extraInfo NVARCHAR2(2000),

    CONSTRAINT FK_Schedule_EventType
        FOREIGN KEY (eventType)
        REFERENCES EventTypes(id),

    CONSTRAINT FK_Schedule_Course
        FOREIGN KEY (curseID)
        REFERENCES Courses(id)
);

CREATE TABLE Homework(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tittle NVARCHAR2(256) NOT NULL,
    description NVARCHAR2(2000),
    type NUMBER NOT NULL,
    assigmentLink NVARCHAR2(1000) NOT NULL,
    curseId NUMBER NOT NULL,
    Status NUMBER NOT NULL,
    DateOfBegin DATE,

    CONSTRAINT FK_Homework_Type
        FOREIGN KEY (type)
        REFERENCES HomeworkTypes(id),

    CONSTRAINT FK_Homework_Course
        FOREIGN KEY (curseId)
        REFERENCES Courses(id),

    CONSTRAINT FK_Homework_Status
        FOREIGN KEY (Status)
        REFERENCES HomeworkStatuses(id)
);

CREATE TABLE Languages(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Lang NVARCHAR2(256) NOT NULL,
    LangCode NVARCHAR2(5) NOT NULL
);


CREATE TABLE LangInCureses
(
    CourseID NUMBER,
    LangID NUMBER,

    CONSTRAINT PK_LangInCureses
        PRIMARY KEY (CourseID, LangID),

    CONSTRAINT FK_LangInCureses_Courses
        FOREIGN KEY (CourseID)
        REFERENCES Courses(id),

    CONSTRAINT FK_LangInCureses_LangID
        FOREIGN KEY (LangID)
        REFERENCES Languages(id)
);


CREATE TABLE StydentComplition(
    StudId NUMBER NOT NULL,
    TaskID NUMBER NOT NULL,
    Status NUMBER NOT NULL,
    Mark NUMBER,
    StudentWork NVARCHAR2(2000),
    Message NVARCHAR2(2000),

    CONSTRAINT PK_StydentComplition
        PRIMARY KEY (StudId, TaskID),

    CONSTRAINT FK_StudentComplition_Task
        FOREIGN KEY (TaskID)
        REFERENCES Homework(id),

    CONSTRAINT FK_StudentComplition_User
        FOREIGN KEY (StudId)
        REFERENCES Users(id),

    CONSTRAINT FK_StudentComplition_Status
        FOREIGN KEY (Status)
        REFERENCES HomeworkExecutionStatuses(id)
);


CREATE TABLE MasteredLang(
    UserId NUMBER NOT NULL,
    LangId NUMBER NOT NULL,
    langLevel  NVARCHAR2(6) NOT NULL,

    CONSTRAINT PK_masteredLang
        PRIMARY KEY(UserId, LangId),

    CONSTRAINT FK_MasteredLang_User
        FOREIGN KEY (UserId)
        REFERENCES Users(id),

    CONSTRAINT FK_MasteredLang_Lang
        FOREIGN KEY (LangId)
        REFERENCES Languages(id)
);


CREATE TABLE TeacherInCourse (
    TeachId NUMBER NOT NULL,
    CourseId NUMBER NOT NULL,

    CONSTRAINT PK_TeacherInCourse 
        PRIMARY KEY (TeachId, CourseId),

    CONSTRAINT FK_TeacherInCourse_User
        FOREIGN KEY (TeachId)
        REFERENCES Users(id),

    CONSTRAINT FK_TeacherInCourse_Course
        FOREIGN KEY (CourseId)
        REFERENCES Courses(id)
);


CREATE TABLE StudentInCourse (
    StudId NUMBER NOT NULL,
    CourseId NUMBER NOT NULL,

    CONSTRAINT PK_StudentInCourse
        PRIMARY KEY (StudId, CourseId),

    CONSTRAINT FK_StudentInCourse_User
        FOREIGN KEY (StudId)
        REFERENCES Users(id),

    CONSTRAINT FK_StudentInCourse_Course
        FOREIGN KEY (CourseId)
        REFERENCES Courses(id)
);